# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-10 12:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hyfy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=36)),
                ('genrename', models.CharField(max_length=36)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hyfy.City')),
            ],
            options={
                'verbose_name_plural': 'genres',
            },
        ),
        migrations.AlterField(
            model_name='venue',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_venue_set', to='hyfy.Genre'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genre_venue_set', to='hyfy.Genre'),
        ),
    ]
