# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-10 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyfy', '0003_auto_20190310_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
