# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-12 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyfy', '0009_auto_20190311_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
