# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-13 18:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hyfy', '0009_auto_20190311_1943'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('text', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hyfy.UserProfile')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hyfy.Venue')),
            ],
            options={
                'verbose_name_plural': 'reviews',
            },
        ),
    ]
