# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-13 19:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hyfy', '0010_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='date',
        ),
    ]
