# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-14 11:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hyfy', '0011_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
    ]
