# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-14 14:12
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyfy', '0014_remove_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.CharField(default='', max_length=100, verbose_name=django.contrib.auth.models.User),
            preserve_default=False,
        ),
    ]
