# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-15 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyfy', '0016_auto_20190314_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spotauth',
            name='user',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='artist0imglink',
            field=models.URLField(default='placeholder', max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='artist0link',
            field=models.URLField(default='placeholder', max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='artist1imglink',
            field=models.URLField(default='placeholder', max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='artist1link',
            field=models.URLField(default='placeholder', max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='artist2imglink',
            field=models.URLField(default='placeholder', max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='artist2link',
            field=models.URLField(default='placeholder', max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='artist3imglink',
            field=models.URLField(default='placeholder', max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='artist3link',
            field=models.URLField(default='placeholder', max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='artist4imglink',
            field=models.URLField(default='placeholder', max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='artist4link',
            field=models.URLField(default='placeholder', max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='artist5imglink',
            field=models.URLField(default='placeholder', max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='artist5link',
            field=models.URLField(default='placeholder', max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='artist6imglink',
            field=models.URLField(default='placeholder', max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='artist6link',
            field=models.URLField(default='placeholder', max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='artist7imglink',
            field=models.URLField(default='placeholder', max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='artist7link',
            field=models.URLField(default='placeholder', max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='artist8imglink',
            field=models.URLField(default='placeholder', max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='artist8link',
            field=models.URLField(default='placeholder', max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='spotifyDisplayName',
            field=models.TextField(default='placeholder', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='spotifyLink',
            field=models.URLField(default='placeholder', max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='spotifyPicture',
            field=models.URLField(default='placeholder', max_length=500),
        ),
        migrations.DeleteModel(
            name='spotAuth',
        ),
    ]
