# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-18 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyfy', '0017_auto_20190315_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='address',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='venue',
            name='website',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
