# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-15 15:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyfy', '0017_review_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2019, 3, 15)),
        ),
    ]
