# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-20 12:14
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyfy', '0019_userprofile_topgenre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name=django.contrib.auth.models.User)),
                ('text', models.CharField(max_length=200)),
            ],
        ),
    ]
